/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        backGroundWhite: "var(--Sys-Surface-Primary)",
        textWhite: "var(--Sys-Surface-Primary)",
        lightBachround: "var(--Sys-Surface-Secondary)",
        secondaryBlack: "var(--Sys-Text-Title-Primary)",
        textBlack: "var(--Sys-Text-Paragraph-Primary)",
        cardBlack: "var(--Sys-Text-Title-Primary)",
        textGray_10: "var(--Sys-Surface-Tertiary)",
        textGray_40: "#AAACB7",
        textGray_1: "#7d8090",
        textGray_2: "#3e4353",
        textGray_3: "#444c5f",
        textGray_4: "var(--Sys-Text-Paragraph-Secondary)",
        textGray_5: "#9295A3",
        textBlue: "#6092FF",
        primaryBlue: "var( --Sys-Text-Title-Brand)",
        navbarBorder: "#dfe0e8",
        buttonBorder: "#b0b5be",
        darkBlue: "#19243A",
        darkBlue_80: "#00124D",
        lightBlue: "var(--light-blue)",
        footerGray: "#98A2B3",
        headerBorder: "var(--header-border)",
        borderPtimery: "var(--Sys-Border-Primary)",
        BorderSecondary: "var(--Sys-Border-Secondary)",
        inviteSectionText: "var(--invite-section-text)",
        inviteSectionCard: "var(--invite-section-card)",
        blueLightToDark: "var(--blue-light-toDark)",
        blueDarkToLight: "var(--blue-dark-tolight)",
        downloadSection: "var(--download-section)",
      },
    },
  },
  plugins: [],
};
